// Class: ReadRuleFit
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : RuleFit::RuleFit
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/00       [394752]
Creator        : jesperhallberg
Date           : Mon Feb 29 12:50:45 2016
Host           : Darwin tennine-slave.macports.org 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
Dir            : /opt/local/libexec/root6/share/doc/root/tutorials/tmva
Training events: 2000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
GDTau: "-1.000000e+00" [Gradient-directed (GD) path: default fit cut-off]
GDTauPrec: "1.000000e-02" [GD path: precision of tau]
GDStep: "1.000000e-02" [GD path: step size]
GDNSteps: "10000" [GD path: number of steps]
GDErrScale: "1.020000e+00" [Stop scan when error > scale*errmin]
fEventsMin: "1.000000e-02" [Minimum fraction of events in a splittable node]
fEventsMax: "5.000000e-01" [Maximum fraction of events in a splittable node]
nTrees: "20" [Number of trees in forest.]
RuleMinDist: "1.000000e-03" [Minimum distance between rules]
MinImp: "1.000000e-03" [Minimum rule importance accepted]
Model: "modrulelinear" [Model to be used]
RuleFitModule: "rftmva" [Which RuleFit module to use]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
LinQuantile: "2.500000e-02" [Quantile of linear terms (removes outliers)]
GDPathEveFrac: "5.000000e-01" [Fraction of events used for the path search]
GDValidEveFrac: "5.000000e-01" [Fraction of events used for the validation]
ForestType: "adaboost" [Method to use for forest generation (AdaBoost or RandomForest)]
RFWorkDir: "./rulefit" [Friedman's RuleFit module (RFF): working dir]
RFNrules: "2000" [RFF: Mximum number of rules]
RFNendnodes: "4" [RFF: Average number of end nodes]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
var1+var2                     myvar1                        myvar1                        myvar1                                                          'F'    [-8.53927993774,7.90235996246]
var1-var2                     myvar2                        myvar2                        Expression 2                                                    'F'    [-3.78471279144,3.88831329346]
var3                          var3                          var3                          Variable 3                    units                             'F'    [-5.3562874794,4.64219379425]
var4                          var4                          var4                          Variable 4                    units                             'F'    [-5.99433326721,4.92254400253]
NSpec 2
var1*2                        spec1                         spec1                         Spectator 1                   units                             'F'    [-9.63254642487,9.15156078339]
var1*3                        spec2                         spec2                         Spectator 2                   units                             'F'    [-14.4488201141,13.7273406982]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadRuleFit : public IClassifierReader {

 public:

   // constructor
   ReadRuleFit( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadRuleFit" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var1+var2", "var1-var2", "var3", "var4" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadRuleFit() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadRuleFit"
};
void   ReadRuleFit::Initialize(){}
void   ReadRuleFit::Clear(){}
double ReadRuleFit::GetMvaValue__( const std::vector<double>& inputValues ) const {
   double rval=9.506618957;
   //
   // here follows all rules ordered in importance (most important first)
   // at the end of each line, the relative importance of the rule is given
   //
   if ((inputValues[3]<1.80343616)) rval+=-3.100879739;   // importance = 0.563
   if ((inputValues[0]<0.2676190734)&&(inputValues[3]<-0.7958202958)) rval+=-1.910557899;   // importance = 0.496
   if ((-0.5951059461<inputValues[2])) rval+=-1.743062371;   // importance = 0.495
   if ((inputValues[2]<-0.5951059461)) rval+=-1.372050957;   // importance = 0.390
   if ((-1.492862821<inputValues[0])&&(inputValues[1]<0.9652557373)) rval+=-1.278406588;   // importance = 0.378
   if ((-0.4962730408<inputValues[1])&&(inputValues[3]<0.3857032359)) rval+=-1.06856064;   // importance = 0.324
   if ((-0.7958202958<inputValues[3])) rval+=-1.204407796;   // importance = 0.313
   if ((-1.492862821<inputValues[0])) rval+=-1.117716699;   // importance = 0.273
   if ((inputValues[0]<-1.492862821)&&(inputValues[1]<0.9652557373)) rval+=-1.088921916;   // importance = 0.243
   if ((inputValues[2]<-0.3832809031)&&(inputValues[3]<-1.315671563)) rval+=-1.137741263;   // importance = 0.232
   if ((inputValues[1]<-0.4962730408)&&(-0.1950056851<inputValues[3])) rval+=-0.8232334753;   // importance = 0.205
   if ((inputValues[1]<-0.4962730408)&&(inputValues[3]<-0.1950056851)) rval+=-0.8410342937;   // importance = 0.183
   if ((0.9652557373<inputValues[1])) rval+=-0.7461432587;   // importance = 0.182
   if ((-2.240825415<inputValues[0])&&(inputValues[0]<-0.6950232387)&&(inputValues[1]<1.330637932)&&(inputValues[3]<-0.6308522224)) rval+=-0.8095553631;   // importance = 0.169
   if ((-1.492862821<inputValues[0])&&(inputValues[2]<0.6597613692)&&(inputValues[3]<0.1868854016)) rval+=-0.4565351261;   // importance = 0.133
   if ((-0.3243100643<inputValues[0])&&(inputValues[3]<1.232548237)) rval+=-0.3552282049;   // importance = 0.109
   if ((-2.275798082<inputValues[0])&&(-0.3479631841<inputValues[2])&&(inputValues[3]<1.986196756)) rval+=-0.3481976921;   // importance = 0.109
   if ((-1.741539598<inputValues[0])&&(-0.4962730408<inputValues[1])&&(0.3857032359<inputValues[3])) rval+=-0.3843746621;   // importance = 0.108
   if ((-0.4962730408<inputValues[1])&&(0.3857032359<inputValues[3])) rval+=-0.382506811;   // importance = 0.108
   if ((0.275416851<inputValues[0])&&(inputValues[0]<1.638878107)&&(inputValues[3]<0.8628248572)) rval+=-0.4621499493;   // importance = 0.108
   if ((inputValues[0]<1.638878107)&&(-1.221790314<inputValues[3])) rval+=0.3582598056;   // importance = 0.103
   if ((-0.4962730408<inputValues[1])&&(inputValues[2]<0.6086985469)&&(inputValues[3]<0.3857032359)) rval+=-0.2731436544;   // importance = 0.082
   if ((-0.9443545341<inputValues[0])&&(1.283584952<inputValues[3])) rval+=-0.3339452755;   // importance = 0.080
   if ((-1.492862821<inputValues[0])&&(-0.1486451924<inputValues[1])&&(inputValues[1]<0.9652557373)) rval+=0.2729502957;   // importance = 0.077
   if ((0.5998735428<inputValues[1])&&(inputValues[2]<-0.2932548225)) rval+=-0.3031448014;   // importance = 0.066
   if ((-2.240825415<inputValues[0])&&(inputValues[1]<1.330637932)&&(inputValues[3]<0.09815495461)) rval+=-0.2160917779;   // importance = 0.065
   if ((-0.4962730408<inputValues[1])&&(0.6086985469<inputValues[2])&&(inputValues[3]<1.475602388)) rval+=-0.3080850756;   // importance = 0.057
   if ((-2.240825415<inputValues[0])&&(inputValues[1]<1.330637932)&&(-0.6308522224<inputValues[3])) rval+=0.1906421563;   // importance = 0.057
   if ((inputValues[1]<-1.22703743)) rval+=0.2497078992;   // importance = 0.055
   if ((-2.240825415<inputValues[0])&&(inputValues[1]<1.330637932)&&(0.2841168046<inputValues[2])&&(inputValues[3]<0.852219224)) rval+=-0.2363452663;   // importance = 0.050
   if ((0.5998735428<inputValues[1])&&(-0.2932548225<inputValues[2])) rval+=-0.204431736;   // importance = 0.046
   if ((-1.2609514<inputValues[1])&&(inputValues[1]<-0.4962730408)&&(inputValues[3]<-0.1950056851)) rval+=-0.238167584;   // importance = 0.042
   if ((-2.240825415<inputValues[0])&&(inputValues[1]<1.330637932)&&(inputValues[2]<0.2841168046)&&(inputValues[3]<0.852219224)) rval+=0.08517596581;   // importance = 0.026
   if ((-0.7099276185<inputValues[0])&&(0.2945204377<inputValues[1])) rval+=0.07295954362;   // importance = 0.020
   if ((inputValues[0]<2.235671043)) rval+=-0.05518759944;   // importance = 0.010
   if ((-1.492862821<inputValues[0])&&(inputValues[0]<0.7181859016)&&(-0.1486451924<inputValues[1])&&(inputValues[1]<0.9652557373)) rval+=0.01713858779;   // importance = 0.004
   //
   // here follows all linear terms
   // at the end of each line, the relative importance of the term is given
   //
   rval+=-0.6898259789*std::min( double(3.451984406), std::max( double(inputValues[0]), double(-3.311891317)));   // importance = 0.715
   rval+=-0.2271537657*std::min( double(2.288625956), std::max( double(inputValues[1]), double(-2.133593798)));   // importance = 0.156
   rval+=-0.05802594139*std::min( double(2.056188107), std::max( double(inputValues[2]), double(-2.117321968)));   // importance = 0.038
   rval+=1.314779827*std::min( double(2.578518867), std::max( double(inputValues[3]), double(-2.314136028)));   // importance = 1.000
   return rval;
}
   inline double ReadRuleFit::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
