// Class: ReadCutsD
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Cuts::CutsD
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/00       [394752]
Creator        : jesperhallberg
Date           : Mon Feb 29 12:50:03 2016
Host           : Darwin tennine-slave.macports.org 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
Dir            : /opt/local/libexec/root6/share/doc/root/tutorials/tmva
Training events: 2000
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "Decorrelate" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
FitMethod: "MC" [Minimisation Method (GA, SA, and MC are the primary methods to be used; the others have been introduced for testing purposes and are depreciated)]
EffMethod: "EffSel" [Selection Method]
# Default:
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
CutRangeMin[0]: "-1.000000e+00" [Minimum of allowed cut range (set per variable)]
    CutRangeMin[1]: "-1.000000e+00"
    CutRangeMin[2]: "-1.000000e+00"
    CutRangeMin[3]: "-1.000000e+00"
CutRangeMax[0]: "-1.000000e+00" [Maximum of allowed cut range (set per variable)]
    CutRangeMax[1]: "-1.000000e+00"
    CutRangeMax[2]: "-1.000000e+00"
    CutRangeMax[3]: "-1.000000e+00"
VarProp[0]: "FSmart" [Categorisation of cuts]
    VarProp[1]: "FSmart"
    VarProp[2]: "FSmart"
    VarProp[3]: "FSmart"
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 4
var1+var2                     myvar1                        myvar1                        myvar1                                                          'F'    [-8.53927993774,7.90235996246]
var1-var2                     myvar2                        myvar2                        Expression 2                                                    'F'    [-3.78471279144,3.88831329346]
var3                          var3                          var3                          Variable 3                    units                             'F'    [-5.3562874794,4.64219379425]
var4                          var4                          var4                          Variable 4                    units                             'F'    [-5.99433326721,4.92254400253]
NSpec 2
var1*2                        spec1                         spec1                         Spectator 1                   units                             'F'    [-9.63254642487,9.15156078339]
var1*3                        spec2                         spec2                         Spectator 2                   units                             'F'    [-14.4488201141,13.7273406982]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadCutsD : public IClassifierReader {

 public:

   // constructor
   ReadCutsD( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadCutsD" ),
        fNvars( 4 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "var1+var2", "var1-var2", "var3", "var4" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -4.60976314544678;
      fVmax[0] = 5.03369092941284;
      fVmin[1] = -3.3960497379303;
      fVmax[1] = 3.28781819343567;
      fVmin[2] = -3.95825099945068;
      fVmax[2] = 4.45810651779175;
      fVmin[3] = -3.40763974189758;
      fVmax[3] = 3.39087462425232;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadCutsD() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fDecTF_1[3][4][4];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[4];
   double fVmax[4];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[4];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadCutsD"
};
   inline double ReadCutsD::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadCutsD::InitTransform_1()
{
   // Decorrelation transformation, initialisation
   fDecTF_1[0][0][0] = 1.28096836896;
   fDecTF_1[0][0][1] = 0.0837324049656;
   fDecTF_1[0][0][2] = -0.145120489232;
   fDecTF_1[0][0][3] = -1.12642473287;
   fDecTF_1[0][1][0] = 0.0837324049656;
   fDecTF_1[0][1][1] = 0.936080467537;
   fDecTF_1[0][1][2] = 0.186807249897;
   fDecTF_1[0][1][3] = -0.274332244079;
   fDecTF_1[0][2][0] = -0.145120489232;
   fDecTF_1[0][2][1] = 0.186807249897;
   fDecTF_1[0][2][2] = 1.83502369394;
   fDecTF_1[0][2][3] = -0.898068064392;
   fDecTF_1[0][3][0] = -1.12642473287;
   fDecTF_1[0][3][1] = -0.274332244079;
   fDecTF_1[0][3][2] = -0.898068064392;
   fDecTF_1[0][3][3] = 2.9279934687;
   fDecTF_1[1][0][0] = 1.25946926842;
   fDecTF_1[1][0][1] = 0.0766418283921;
   fDecTF_1[1][0][2] = -0.136986622156;
   fDecTF_1[1][0][3] = -1.09943029483;
   fDecTF_1[1][1][0] = 0.0766418283921;
   fDecTF_1[1][1][1] = 0.921546711518;
   fDecTF_1[1][1][2] = 0.176080487371;
   fDecTF_1[1][1][3] = -0.251926194125;
   fDecTF_1[1][2][0] = -0.136986622156;
   fDecTF_1[1][2][1] = 0.176080487371;
   fDecTF_1[1][2][2] = 1.87466711226;
   fDecTF_1[1][2][3] = -0.939553470669;
   fDecTF_1[1][3][0] = -1.09943029483;
   fDecTF_1[1][3][1] = -0.251926194125;
   fDecTF_1[1][3][2] = -0.939553470669;
   fDecTF_1[1][3][3] = 2.94820757229;
   fDecTF_1[2][0][0] = 1.1321265708;
   fDecTF_1[2][0][1] = 0.0413265752415;
   fDecTF_1[2][0][2] = -0.19739315044;
   fDecTF_1[2][0][3] = -0.800770807794;
   fDecTF_1[2][1][0] = 0.0413265752415;
   fDecTF_1[2][1][1] = 0.91680331692;
   fDecTF_1[2][1][2] = 0.167985680373;
   fDecTF_1[2][1][3] = -0.168434129894;
   fDecTF_1[2][2][0] = -0.19739315044;
   fDecTF_1[2][2][1] = 0.167985680373;
   fDecTF_1[2][2][2] = 1.82053288163;
   fDecTF_1[2][2][3] = -0.806810475019;
   fDecTF_1[2][3][0] = -0.800770807794;
   fDecTF_1[2][3][1] = -0.168434129894;
   fDecTF_1[2][3][2] = -0.806810475019;
   fDecTF_1[2][3][3] = 2.18311056733;
}

//_______________________________________________________________________
inline void ReadCutsD::Transform_1( std::vector<double>& iv, int cls) const
{
   // Decorrelation transformation
   if (cls < 0 || cls > 2) {
       if (2 > 1 ) cls = 2;
       else cls = 2;
   }

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
   } 

   std::vector<double> tv;
   for (int i=0; i<4;i++) {
      double v = 0;
      for (int j=0; j<4; j++)
         v += iv[indicesGet.at(j)] * fDecTF_1[cls][i][j];
      tv.push_back(v);
   }
   for (int i=0; i<4;i++) iv[indicesPut.at(i)] = tv[i];
}

//_______________________________________________________________________
inline void ReadCutsD::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadCutsD::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
